services:
  gateway:
    image: dev_code_notes_gateway
    build:
      context: .
      args:
        NODE_IMAGE_TAG: ${NODE_IMAGE_TAG}
    environment:
      TZ: ${TZ}
    ports:
      - 3000:3000
    volumes:
      - ./.ssl/localhost.crt.pem:/app/volumes/ssl/localhost.crt.pem
      - ./.ssl/localhost.key.pem:/app/volumes/ssl/localhost.key.pem