name: code_notes_gateway

run-name: ${{ github.event.head_commit.message }}
on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  # dev and prod
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: npm ci
      - run: npx tsc -b

  # prod
  push_to_Dockerhub:
    # NOTE: ${{}} syntax does not work here
    if: (github.head_ref || github.ref_name) == 'main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: move .env vars to pipeline
        run: |
          echo $(cat .env | grep '^APP_VERSION=.*$') >> $GITHUB_ENV
          echo $(cat .env | grep '^NODE_IMAGE_TAG=.*$') >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          # explicitly specify context in order for .dockerignore to be considered
          context: .
          build-args: |
            NODE_IMAGE_TAG=${{ env.NODE_IMAGE_TAG }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/code_notes_gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/code_notes_gateway:${{ env.APP_VERSION }}

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: push_to_Dockerhub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v3
        with:
          config_file: .github/workflows/config.ovpn
          client_key: ${{ secrets.OPEN_VPN_PRIVATE_KEY }}

      - name: Move .env vars to pipeline env
        run: |
          echo $(cat .env | grep '^PORT=.*$') >> $GITHUB_ENV
        shell: bash

      - name: Write env to server .env file, then pull, rerun and clean up
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          script: |
            chmod 777 ./${{ vars.SSH_TARGET_FOLDER }}/writeToEnvFile.sh 
            ./${{ vars.SSH_TARGET_FOLDER }}/writeToEnvFile.sh \
              GATEWAY_PORT='${{ env.GATEWAY_PORT }}'

            docker compose -f './${{ vars.SSH_TARGET_FOLDER }}/docker-compose.yml' pull gateway
            yes | docker rm $(docker container ls --all --filter=ancestor=$(docker images -f "dangling=true" -q) --format "{{.ID}}") --force
            yes | docker image rm $(docker images -f "dangling=true" -q)
            docker compose -f './${{ vars.SSH_TARGET_FOLDER }}/docker-compose.yml' up gateway -d
            yes | docker volume prune
